### ISSUE TITLE
Улучшение кода

### ISSUE THREAD

**Issue by BlitDev** [Yavorskui/GulPython#1]
Этот код можно улучшить так:
```python
count = 1000 #  Задаем изначальное значение

print("Я, гуль!") #  Перед счётом

while one > 0:
    print(f"{count} - 7 = {count - 7}") #  Выводим
    
    #  Меняем изначальное значение
    count -= 7
```

И да, в оригинальном меме, слова "Я, гуль" произносятся перед счётом, так что ты ошибся. Я кстати запилил свою версию ток на C#, если интересно, чекни.

Ты как давно кодишь, у тебя дикий говнокод, и кажется будто ты ещё многого не знаешь, я просто тоже с питона начинал.

**Comment by Yavorskui** [comment]
Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
В любом случае спасибо :)

**Comment by BlitDev** [comment]
> Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
> Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
> В любом случае спасибо :)

Хаха я тоже по приколу issue открыл) Если хочешь стать норм кодером, попробуй изучить JavaScript/C#

**Comment by BlitDev** [comment]
> > Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
> > Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
> > В любом случае спасибо :)
> 
> Хаха я тоже по приколу issue открыл) Если хочешь стать норм кодером, попробуй изучить JavaScript/C#

Питон не даст понимания парадигм программирования, он слишком упрощен

**Comment by Yavorskui** [comment]
> > > Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
> > > Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
> > > В любом случае спасибо :)
> > 
> > 
> > Хаха я тоже по приколу issue открыл) Если хочешь стать норм кодером, попробуй изучить JavaScript/C#
> 
> Питон не даст понимания парадигм программирования, он слишком упрощен

JavaScript я изучал в один период и даже неплохо получалось, но из-за не хватки времени забросил. Насчёт C# тож были попытки, но дальше первого урока не зашёл. Хочу Джаву изучить или до Шарпа вернусь, но как-то позже.

**Comment by BlitDev** [comment]
> > > > Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
> > > > Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
> > > > В любом случае спасибо :)
> > > 
> > > 
> > > Хаха я тоже по приколу issue открыл) Если хочешь стать норм кодером, попробуй изучить JavaScript/C#
> > 
> > Питон не даст понимания парадигм программирования, он слишком упрощен
> 
> JavaScript я изучал в один период и даже неплохо получалось, но из-за не хватки времени забросил. Насчёт C# тож были попытки, но дальше первого урока не зашёл. Хочу Джаву изучить или до Шарпа вернусь, но как-то позже.

Ты смотрел SimpleCode? Он великолепно объясняет, он сишарпист

**Comment by Yavorskui** [comment]
> > > > > Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
> > > > > Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
> > > > > В любом случае спасибо :)
> > > > 
> > > > 
> > > > Хаха я тоже по приколу issue открыл) Если хочешь стать норм кодером, попробуй изучить JavaScript/C#
> > > 
> > > 
> > > Питон не даст понимания парадигм программирования, он слишком упрощен
> > 
> > 
> > JavaScript я изучал в один период и даже неплохо получалось, но из-за не хватки времени забросил. Насчёт C# тож были попытки, но дальше первого урока не зашёл. Хочу Джаву изучить или до Шарпа вернусь, но как-то позже.
> 
> Ты смотрел SimpleCode? Он великолепно объясняет, он сишарпист

Я текстовые уроки проходил. Но за подсказку спасибо) Может на досуге, сяду посмоторю.

**Comment by BlitDev** [comment]
> > > > > > Этот код я написал за 3 минуты, а единственное как я изучал Пайтон, это видео ХаудиХо.
> > > > > > Кодером я себя не назову, а пост сделал просто для прикола чтобы мой Гитхаб пустым не стоял.
> > > > > > В любом случае спасибо :)
> > > > > 
> > > > > 
> > > > > Хаха я тоже по приколу issue открыл) Если хочешь стать норм кодером, попробуй изучить JavaScript/C#
> > > > 
> > > > 
> > > > Питон не даст понимания парадигм программирования, он слишком упрощен
> > > 
> > > 
> > > JavaScript я изучал в один период и даже неплохо получалось, но из-за не хватки времени забросил. Насчёт C# тож были попытки, но дальше первого урока не зашёл. Хочу Джаву изучить или до Шарпа вернусь, но как-то позже.
> > 
> > 
> > Ты смотрел SimpleCode? Он великолепно объясняет, он сишарпист
> 
> Я текстовые уроки проходил. Но за подсказку спасибо) Может на досуге, сяду посмоторю.

Удачи. К сожалению SimpleCode давно не выпускал новых видео. Но надежда, что он ещё не забросил канал, ещё остаётся. Отвращение вызывает смотреть уроки по C#, не от симплкода, это лучшие уроки, под каждым его видео, 95% комментов о том как он круто объясняет
